# Generated by Django 3.1.5 on 2021-02-13 14:06

from django.db import migrations


def add_last_name(apps, schema_editor):
    Customer = apps.get_model("main", "Customer")
    for customer in Customer.objects.all():
        customer.last_name = None
        customer.save


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_customer_last_name'),
    ]

    operations = [
        migrations.RunPython(add_last_name)
    ]
