# Generated by Django 3.1.5 on 2021-01-25 12:02
from django.db import migrations


def not_populate_title(apps, schema_editor):
    Product = apps.get_model("main", "Product")
    for product in Product.objects.all():
        product.title = None
        product.save


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_title'),
    ]

    operations = [
        migrations.RunPython(not_populate_title)
    ]
