# Generated by Django 3.1.5 on 2021-02-16 13:44

from django.db import migrations


def add_subscriber(apps, schema_editor):
    Customer = apps.get_model("main", "Customer")
    for customer in Customer.objects.all():
        customer.subscriber = None
        customer.save


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210213_1406'),
    ]

    operations = [
        migrations.RunPython(add_subscriber)
    ]
