# Generated by Django 3.1.5 on 2021-02-03 12:42

from django.db import migrations


def not_populate_fields_customer(apps, schema_editor):
    Customer = apps.get_model("main", "Customer")
    for customer in Customer.objects.all():
        customer.last_name = "Smith"
        customer.email = "Smith@gmail.com"
        customer.save


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210125_1202'),
    ]

    operations = [
        migrations.RunPython(not_populate_fields_customer)
    ]