# Generated by Django 3.1.5 on 2021-02-17 11:11

from django.db import migrations


def add_create_date_product(apps, schema_editor):
    Product = apps.get_model("main", "Product")
    for product in Product.objects.all():
        product.add_date = None
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210216_1403'),
    ]

    operations = [
        migrations.RunPython(add_create_date_product),
    ]
