# Generated by Django 3.1.5 on 2021-03-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_view',
            field=models.IntegerField(default=0),
        ),
    ]
